In [1]:
import numpy as np

In [2]:
import pandas as pd
import os

csv_directory = '/Users/micah.mathews/Documents/wager_ai/lol_data/data_extraction'
csv_files = [
    "2023_LoL_esports_match_data_from_OraclesElixir.csv",
    "2022_LoL_esports_match_data_from_OraclesElixir.csv",
    "2021_LoL_esports_match_data_from_OraclesElixir.csv",
    "2020_LoL_esports_match_data_from_OraclesElixir.csv",
    "2019_LoL_esports_match_data_from_OraclesElixir.csv",
    "2018_LoL_esports_match_data_from_OraclesElixir.csv",
    "2017_LoL_esports_match_data_from_OraclesElixir.csv",
    "2016_LoL_esports_match_data_from_OraclesElixir.csv",
    "2015_LoL_esports_match_data_from_OraclesElixir.csv"
]

# Create an empty DataFrame
combined_df = pd.DataFrame()

for csv_file in csv_files:
    file_path = os.path.join(csv_directory, csv_file)
    try:
        df = pd.read_csv(file_path)
        combined_df = pd.concat([combined_df, df], ignore_index=True)
        print(f"Appended: {csv_file}")
    except FileNotFoundError:
        print(f"File not found: {csv_file}")
    except Exception as e:
        print(f"Error while reading {csv_file}: {e}")

print(combined_df)

Appended: 2023_LoL_esports_match_data_from_OraclesElixir.csv

/var/folders/5w/5hzxm109285f2kz_4q6tm5yw0000gn/T/ipykernel_21103/3742020193.py:23: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)

Appended: 2022_LoL_esports_match_data_from_OraclesElixir.csv
Appended: 2021_LoL_esports_match_data_from_OraclesElixir.csv
Appended: 2020_LoL_esports_match_data_from_OraclesElixir.csv
Appended: 2019_LoL_esports_match_data_from_OraclesElixir.csv
Appended: 2018_LoL_esports_match_data_from_OraclesElixir.csv
Appended: 2017_LoL_esports_match_data_from_OraclesElixir.csv
Appended: 2016_LoL_esports_match_data_from_OraclesElixir.csv
Appended: 2015_LoL_esports_match_data_from_OraclesElixir.csv
                       gameid datacompleteness  \
0       ESPORTSTMNT06_2753012         complete
1       ESPORTSTMNT06_2753012         complete
2       ESPORTSTMNT06_2753012         complete
3       ESPORTSTMNT06_2753012         complete
4       ESPORTSTMNT06_2753012         complete
...                       ...              ...
846223           FRA1TMNT2/92         complete
846224           FRA1TMNT2/92         complete
846225           FRA1TMNT2/92         complete
846226           FRA1TMNT2/92         complete
846227           FRA1TMNT2/92         complete

                                                      url league  year  \
0                                                     NaN   LFL2  2023
1                                                     NaN   LFL2  2023
2                                                     NaN   LFL2  2023
3                                                     NaN   LFL2  2023
4                                                     NaN   LFL2  2023
...                                                   ...    ...   ...
846223  http://matchhistory.na.leagueoflegends.com/en/...    IEM  2016
846224  http://matchhistory.na.leagueoflegends.com/en/...    IEM  2016
846225  http://matchhistory.na.leagueoflegends.com/en/...    IEM  2016
846226  http://matchhistory.na.leagueoflegends.com/en/...    IEM  2016
846227  http://matchhistory.na.leagueoflegends.com/en/...    IEM  2016

         split  playoffs                 date  game  patch  ...  opp_csat15  \
0       Spring         0  2023-01-10 17:07:16   1.0  13.01  ...       131.0
1       Spring         0  2023-01-10 17:07:16   1.0  13.01  ...       117.0
2       Spring         0  2023-01-10 17:07:16   1.0  13.01  ...       162.0
3       Spring         0  2023-01-10 17:07:16   1.0  13.01  ...       122.0
4       Spring         0  2023-01-10 17:07:16   1.0  13.01  ...         3.0
...        ...       ...                  ...   ...    ...  ...         ...
846223     NaN         0  2015-12-20 20:24:49   5.0   5.23  ...       117.0
846224     NaN         0  2015-12-20 20:24:49   5.0   5.23  ...       136.0
846225     NaN         0  2015-12-20 20:24:49   5.0   5.23  ...        16.0
846226     NaN         0  2015-12-20 20:24:49   5.0   5.23  ...       373.0
846227     NaN         0  2015-12-20 20:24:49   5.0   5.23  ...       389.0

       golddiffat15 xpdiffat15 csdiffat15 killsat15 assistsat15 deathsat15  \
0             322.0      263.0       12.0       0.0         0.0        0.0
1            -357.0    -1323.0      -43.0       0.0         0.0        0.0
2            -479.0     -324.0      -26.0       0.0         0.0        0.0
3             200.0      292.0       20.0       0.0         0.0        0.0
4            -216.0     -579.0        0.0       0.0         0.0        1.0
...             ...        ...        ...       ...         ...        ...
846223        369.0     -339.0       -7.0       2.0         1.0        1.0
846224       -359.0    -1397.0      -21.0       0.0         1.0        0.0
846225        250.0     -110.0        4.0       0.0         4.0        1.0
846226       -760.0      814.0       16.0       4.0         9.0        4.0
846227        760.0     -814.0      -16.0       4.0        10.0        4.0

       opp_killsat15 opp_assistsat15 opp_deathsat15
0                0.0             0.0            0.0
1                0.0             0.0            0.0
2                0.0             0.0            0.0
3                1.0             0.0            0.0
4                0.0             1.0            0.0
...              ...             ...            ...
846223           0.0             4.0            1.0
846224           0.0             2.0            0.0
846225           1.0             2.0            1.0
846226           4.0            10.0            4.0
846227           4.0             9.0            4.0

[846228 rows x 123 columns]

In [3]:
df = combined_df
pd.set_option('display.max_columns', None)
df

,gameid,datacompleteness,url,league,year,split,playoffs,date,game,patch,participantid,side,position,playername,playerid,teamname,teamid,champion,ban1,ban2,ban3,ban4,ban5,gamelength,result,kills,deaths,assists,teamkills,teamdeaths,doublekills,triplekills,quadrakills,pentakills,firstblood,firstbloodkill,firstbloodassist,firstbloodvictim,team kpm,ckpm,firstdragon,dragons,opp_dragons,elementaldrakes,opp_elementaldrakes,infernals,mountains,clouds,oceans,chemtechs,hextechs,dragons (type unknown),elders,opp_elders,firstherald,heralds,opp_heralds,firstbaron,barons,opp_barons,firsttower,towers,opp_towers,firstmidtower,firsttothreetowers,turretplates,opp_turretplates,inhibitors,opp_inhibitors,damagetochampions,dpm,damageshare,damagetakenperminute,damagemitigatedperminute,wardsplaced,wpm,wardskilled,wcpm,controlwardsbought,visionscore,vspm,totalgold,earnedgold,earned gpm,earnedgoldshare,goldspent,gspd,total cs,minionkills,monsterkills,monsterkillsownjungle,monsterkillsenemyjungle,cspm,goldat10,xpat10,csat10,opp_goldat10,opp_xpat10,opp_csat10,golddiffat10,xpdiffat10,csdiffat10,killsat10,assistsat10,deathsat10,opp_killsat10,opp_assistsat10,opp_deathsat10,goldat15,xpat15,csat15,opp_goldat15,opp_xpat15,opp_csat15,golddiffat15,xpdiffat15,csdiffat15,killsat15,assistsat15,deathsat15,opp_killsat15,opp_assistsat15,opp_deathsat15
0,ESPORTSTMNT06_2753012,complete,NaN,LFL2,2023,Spring,0,2023-01-10 17:07:16,1.0,13.01,1,Blue,top,Wylenz,oe:player:60aff1184bec1d2b2efdae84f5b6e3e,Klanik Esport,oe:team:0ade5e44c23039bca133eee58ec1b83,Jax,Sylas,Caitlyn,Wukong,Akali,Yone,2612,1,4,0,6,13,7,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.2986,0.4594,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,0.0,14283.0,328.0934,0.150027,719.5406,878.9127,20.0,0.4594,5.0,0.1149,11.0,49.0,1.1256,18855.0,13251.0,304.3874,0.295868,15955.0,NaN,399.0,367.0,32.0,NaN,NaN,9.1654,3163.0,4772.0,83.0,3087.0,4814.0,81.0,76.0,-42.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,5059.0,7946.0,143.0,4737.0,7683.0,131.0,322.0,263.0,12.0,0.0,0.0,0.0,0.0,0.0,0.0
1,ESPORTSTMNT06_2753012,complete,NaN,LFL2,2023,Spring,0,2023-01-10 17:07:16,1.0,13.01,2,Blue,jng,Julbu,oe:player:fd78e127e45463dcfc2ea3836af0335,Klanik Esport,oe:team:0ade5e44c23039bca133eee58ec1b83,Poppy,Sylas,Caitlyn,Wukong,Akali,Yone,2612,1,2,2,4,13,7,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.2986,0.4594,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,6219.0,142.8560,0.065324,847.3047,1513.9663,18.0,0.4135,11.0,0.2527,17.0,61.0,1.4012,12082.0,6478.0,148.8055,0.144640,11675.0,NaN,159.0,23.0,136.0,NaN,NaN,3.6524,3035.0,3302.0,54.0,2948.0,3140.0,66.0,87.0,162.0,-12.0,0.0,0.0,0.0,0.0,0.0,0.0,4325.0,4637.0,74.0,4682.0,5960.0,117.0,-357.0,-1323.0,-43.0,0.0,0.0,0.0,0.0,0.0,0.0
2,ESPORTSTMNT06_2753012,complete,NaN,LFL2,2023,Spring,0,2023-01-10 17:07:16,1.0,13.01,3,Blue,mid,Sintax,oe:player:baf7147fedeec5de54ca1f240952a3f,Klanik Esport,oe:team:0ade5e44c23039bca133eee58ec1b83,Taliyah,Sylas,Caitlyn,Wukong,Akali,Yone,2612,1,2,2,11,13,7,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.2986,0.4594,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,27028.0,620.8576,0.283899,365.3522,323.7289,23.0,0.5283,10.0,0.2297,7.0,49.0,1.1256,15722.0,10118.0,232.4196,0.225914,14525.0,NaN,337.0,287.0,50.0,NaN,NaN,7.7412,3117.0,4927.0,85.0,3455.0,5174.0,103.0,-338.0,-247.0,-18.0,0.0,0.0,0.0,0.0,0.0,0.0,4956.0,7772.0,136.0,5435.0,8096.0,162.0,-479.0,-324.0,-26.0,0.0,0.0,0.0,0.0,0.0,0.0
3,ESPORTSTMNT06_2753012,complete,NaN,LFL2,2023,Spring,0,2023-01-10 17:07:16,1.0,13.01,4,Blue,bot,Axelent,oe:player:8204ca38dc1c42012b5d53131271eb1,Klanik Esport,oe:team:0ade5e44c23039bca133eee58ec1b83,Ezreal,Sylas,Caitlyn,Wukong,Akali,Yone,2612,1,5,1,7,13,7,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.2986,0.4594,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,0.0,42005.0,964.8928,0.441215,398.4533,234.3721,17.0,0.3905,6.0,0.1378,5.0,47.0,1.0796,17332.0,11728.0,269.4028,0.261862,15225.0,NaN,370.0,345.0,25.0,NaN,NaN,8.4992,3344.0,3377.0,94.0,3015.0,2948.0,75.0,329.0,429.0,19.0,0.0,0.0,0.0,0.0,0.0,0.0,5217.0,5647.0,142.0,5017.0,5355.0,122.0,200.0,292.0,20.0,0.0,0.0,0.0,1.0,0.0,0.0
4,ESPORTSTMNT06_2753012,complete,NaN,LFL2,2023,Spring,0,2023-01-10 17:07:16,1.0,13.01,5,Blue,sup,Wixo,oe:player:bb97cd2e43cb0855f6485e6f9e93ea2,Klanik Esport,oe:team:0ade5e44c23039bca133eee58ec1b83,Karma,Sylas,Caitlyn,Wukong,Akali,Yone,2612,1,0,2,10,13,7,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.2986,0.4594,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,5668.0,130.1991,0.059536,360.2757,284.1501,52.0,1.1945,8.0,0.1838,15.0,106.0,2.4349,8816.0,3212.0,73.7825,0.071716,8125.0,NaN,21.0,17.0,4.0,NaN,NaN,0.4824,1953.0,2367.0,1.0,2032.0,2825.0,3.0,-79.0,-458.0,-2.0,0.0,0.0,0.0,0.0,0.0,0.0,2827.0,3218.0,3.0,3043.0,3797.0,3.0,-216.0,-579.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
846223,FRA1TMNT2/92,complete,http://matchhistory.na.leagueoflegends.com/en/...,IEM,2016,NaN,0,2015-12-20 20:24:49,5.0,5.23,8,Red,mid,Doinb,oe:player:9b73925063fe3714ebb4e8c10f551c0,Qiao Gu Reapers,oe:team:1664f819c4a19a12d748a78a1ca0d7d,Cassiopeia,Bard,Gangplank,Varus,NaN,NaN,2075,0,3,3,2,7,11,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.2024,0.5205,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,15560.0,449.9277,0.311455,448.5398,0.0000,20.0,0.5783,4.0,0.1157,2.0,0.0,0.0000,12300.0,7812.0,225.8892,0.243609,11550.0,NaN,294.0,284.0,10.0,10.0,0.0,8.5012,3009.0,4081.0,67.0,3169.0,4349.0,83.0,-160.0,-268.0,-16.0,0.0,0.0,0.0,0.0,0.0,0.0,5257.0,6202.0,110.0,4888.0,6541.0,117.0,369.0,-339.0,-7.0,2.0,1.0,1.0,0.0,4.0,1.0
846224,FRA1TMNT2/92,complete,http://matchhistory.na.leagueoflegends.com/en/...,IEM,2016,NaN,0,2015-12-20 20:24:49,5.0,5.23,9,Red,bot,Happy,oe:player:ef97b40b2245d3690c745cd6e8c663d,Qiao Gu Reapers,oe:team:1664f819c4a19a12d748a78a1ca0d7d,Tristana,Bard,Gangplank,Varus,NaN,NaN,2075,0,0,2,3,7,11,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.2024,0.5205,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,10215.0,295.3735,0.204468,269.6964,0.0000,9.0,0.2602,14.0,0.4048,1.0,0.0,0.0000,11305.0,6817.0,197.1181,0.212580,10175.0,NaN,278.0,266.0,12.0,11.0,1.0,8.0386,3302.0,2832.0,72.0,3421.0,4011.0,90.0,-119.0,-1179.0,-18.0,0.0,0.0,0.0,0.0,0.0,0.0,4856.0,4905.0,115.0,5215.0,6302.0,136.0,-359.0,-1397.0,-21.0,0.0,1.0,0.0,0.0,2.0,0.0
846225,FRA1TMNT2/92,complete,http://matchhistory.na.leagueoflegends.com/en/...,IEM,2016,NaN,0,2015-12-20 20:24:49,5.0,5.23,10,Red,sup,Mor,oe:player:3a51d2dae2a4c583a3f70ceed2e17ff,Qiao Gu Reapers,oe:team:1664f819c4a19a12d748a78a1ca0d7d,Trundle,Bard,Gangplank,Varus,NaN,NaN,2075,0,0,1,7,7,11,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.2024,0.5205,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,3072.0,88.8289,0.061490,412.9157,0.0000,53.0,1.5325,13.0,0.3759,7.0,0.0,0.0000,8506.0,4018.0,116.1831,0.125294,8075.0,NaN,64.0,64.0,0.0,0.0,0.0,1.8506,2182.0,2230.0,11.0,1807.0,2074.0,9.0,375.0,156.0,2.0,0.0,1.0,0.0,0.0,0.0,1.0,3443.0,3632.0,20.0,3193.0,3742.0,16.0,250.0,-110.0,4.0,0.0,4.0,1.0,1.0,2.0,1.0
846226,FRA1TMNT2/92,complete,http://matchhistory.na.leagueoflegends.com/en/...,IEM,2016,NaN,0,2015-12-20 20:24:49,5.0,5.23,100,Blue,team,NaN,NaN,ESC Ever,oe:team:2e32a1985132a6c92ac8d39a3d158f0,NaN,Viktor,Soraka,Nidalee,NaN,NaN,2075,1,11,7,24,11,7,2.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,0.3181,0.5205,0.0,0.0,0.0,NaN,NaN,0.0,0.0,0.0,0.0,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,8.0,2.0,0.0,1.0,NaN,NaN,1.0,0.0,48858.0,1412.7614,NaN,2621.9277,0.0000,123.0,3.5566,70.0,2.0241,18.0,0.0,0.0000,65767.0,43326.0,1252.8000,NaN,56975.0,0.102399,NaN,995.0,179.0,137.0,42.0,33.9470,13224.0,16306.0,251.0,14384.0,15602.0,228.0,-1160.0,704.0,23.0,0.0,0.0,1.0,1.0,2.0,0.0,21891.0,26474.0,389.0,22651.0,25660.0,373.0,-760.0,814.0,16.0,4.0,9.0,4.0,4.0,10.0,4.0
846227,FRA1TMNT2/92,complete,http://matchhistory.na.leagueoflegends.com/en/...,IEM,2016,NaN,0,2015-12-20 20:24:49,5.0,5.23,200,Red,team,NaN,NaN,Qiao Gu Reapers,oe:team:1664f819c4a19a12d748a78a1ca0d7d,NaN,Bard,Gangplank,Varus,NaN,NaN,2075,0,7,11,18,7,11,0.0,0.0,0.0,0.0,1.0,NaN,NaN,NaN,0.2024,0.5205,1.0,0.0,0.0,NaN,NaN,0.0,0.0,0.0,0.0,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,2.0,8.0,1.0,0.0,NaN,NaN,0.0,1.0,49959.0,1444.5976,NaN,2137.4458,0.0000,131.0,3.7880,59.0,1.7060,20.0,0.0,0.0000,54508.0,32067.0,927.2386,NaN,51425.0,-0.102399,NaN,877.0,124.0,110.0,14.0,28.9446,14384.0,15602.0,228.0,13224.0,16306.0,251.0,1160.0,-704.0,-23.0,1.0,2.0,0.0,0.0,0.0,1.0,22651.0,25660.0,373.0,21891.0,26474.0,389.0,760.0,-814.0,-16.0,4.0,10.0,4.0,4.0,9.0,4.0

In [4]:
selected_columns = ['gameid', 'datacompleteness', 'url', 'league', 'year', 'split', 'playoffs', 'date', 'game', 'patch', 'side', 'position', 'playername', 'teamname', "result", 'champion']
df = df[selected_columns]
df

,gameid,datacompleteness,url,league,year,split,playoffs,date,game,patch,side,position,playername,teamname,result,champion
0,ESPORTSTMNT06_2753012,complete,NaN,LFL2,2023,Spring,0,2023-01-10 17:07:16,1.0,13.01,Blue,top,Wylenz,Klanik Esport,1,Jax
1,ESPORTSTMNT06_2753012,complete,NaN,LFL2,2023,Spring,0,2023-01-10 17:07:16,1.0,13.01,Blue,jng,Julbu,Klanik Esport,1,Poppy
2,ESPORTSTMNT06_2753012,complete,NaN,LFL2,2023,Spring,0,2023-01-10 17:07:16,1.0,13.01,Blue,mid,Sintax,Klanik Esport,1,Taliyah
3,ESPORTSTMNT06_2753012,complete,NaN,LFL2,2023,Spring,0,2023-01-10 17:07:16,1.0,13.01,Blue,bot,Axelent,Klanik Esport,1,Ezreal
4,ESPORTSTMNT06_2753012,complete,NaN,LFL2,2023,Spring,0,2023-01-10 17:07:16,1.0,13.01,Blue,sup,Wixo,Klanik Esport,1,Karma
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
846223,FRA1TMNT2/92,complete,http://matchhistory.na.leagueoflegends.com/en/...,IEM,2016,NaN,0,2015-12-20 20:24:49,5.0,5.23,Red,mid,Doinb,Qiao Gu Reapers,0,Cassiopeia
846224,FRA1TMNT2/92,complete,http://matchhistory.na.leagueoflegends.com/en/...,IEM,2016,NaN,0,2015-12-20 20:24:49,5.0,5.23,Red,bot,Happy,Qiao Gu Reapers,0,Tristana
846225,FRA1TMNT2/92,complete,http://matchhistory.na.leagueoflegends.com/en/...,IEM,2016,NaN,0,2015-12-20 20:24:49,5.0,5.23,Red,sup,Mor,Qiao Gu Reapers,0,Trundle
846226,FRA1TMNT2/92,complete,http://matchhistory.na.leagueoflegends.com/en/...,IEM,2016,NaN,0,2015-12-20 20:24:49,5.0,5.23,Blue,team,NaN,ESC Ever,1,NaN
846227,FRA1TMNT2/92,complete,http://matchhistory.na.leagueoflegends.com/en/...,IEM,2016,NaN,0,2015-12-20 20:24:49,5.0,5.23,Red,team,NaN,Qiao Gu Reapers,0,NaN

In [5]:
df.loc[:, 'date'] = pd.to_datetime(df['date'])

df.sort_values(by='date', inplace=True)

grouped = df.groupby(['playername', 'champion'])

total_games = grouped['result'].cumcount()
total_wins = grouped['result'].cumsum()

win_rate = total_wins / total_games

df.loc[:, 'player_champ_winrate'] = win_rate

df

/var/folders/5w/5hzxm109285f2kz_4q6tm5yw0000gn/T/ipykernel_21103/2021407772.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.loc[:, 'date'] = pd.to_datetime(df['date'])
/var/folders/5w/5hzxm109285f2kz_4q6tm5yw0000gn/T/ipykernel_21103/2021407772.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.sort_values(by='date', inplace=True)
/var/folders/5w/5hzxm109285f2kz_4q6tm5yw0000gn/T/ipykernel_21103/2021407772.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.loc[:, 'player_champ_winrate'] = win_rate

,gameid,datacompleteness,url,league,year,split,playoffs,date,game,patch,side,position,playername,teamname,result,champion,player_champ_winrate
824446,TRKR1/440018,complete,http://matchhistory.na.leagueoflegends.com/en/...,OGN,2015,Spring,0,2015-01-07 08:56:44,1.0,4.21,Blue,team,NaN,NaJin e-mFire,1,NaN,NaN
824445,TRKR1/440018,complete,http://matchhistory.na.leagueoflegends.com/en/...,OGN,2015,Spring,0,2015-01-07 08:56:44,1.0,4.21,Red,sup,Wolf,SK Telecom T1,0,Thresh,NaN
824444,TRKR1/440018,complete,http://matchhistory.na.leagueoflegends.com/en/...,OGN,2015,Spring,0,2015-01-07 08:56:44,1.0,4.21,Red,bot,Bang,SK Telecom T1,0,Tristana,NaN
824443,TRKR1/440018,complete,http://matchhistory.na.leagueoflegends.com/en/...,OGN,2015,Spring,0,2015-01-07 08:56:44,1.0,4.21,Red,mid,Faker,SK Telecom T1,0,Xerath,NaN
824442,TRKR1/440018,complete,http://matchhistory.na.leagueoflegends.com/en/...,OGN,2015,Spring,0,2015-01-07 08:56:44,1.0,4.21,Red,jng,Bengi,SK Telecom T1,0,Lee Sin,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
110252,ESPORTSTMNT04_2690755,complete,NaN,UL,2023,NaN,1,2023-08-04 18:01:54,4.0,13.14,Red,bot,Ice,Zero Tenacity,0,Xayah,0.750000
110253,ESPORTSTMNT04_2690755,complete,NaN,UL,2023,NaN,1,2023-08-04 18:01:54,4.0,13.14,Red,sup,kabbie,Zero Tenacity,0,Nautilus,0.588235
110254,ESPORTSTMNT04_2690755,complete,NaN,UL,2023,NaN,1,2023-08-04 18:01:54,4.0,13.14,Blue,team,NaN,Alior Bank Team,1,NaN,1.000000
110255,ESPORTSTMNT04_2690755,complete,NaN,UL,2023,NaN,1,2023-08-04 18:01:54,4.0,13.14,Red,team,NaN,Zero Tenacity,0,NaN,1.000000
110248,ESPORTSTMNT04_2690755,complete,NaN,UL,2023,NaN,1,2023-08-04 18:01:54,4.0,13.14,Blue,sup,minemaciek,Alior Bank Team,1,Rell,1.000000

In [6]:
grouped = df.groupby(['champion', 'patch'])

total_games = grouped['result'].cumcount()
total_wins = grouped['result'].cumsum()

win_rate = total_wins / total_games
win_rate[total_games == 0] = np.nan

df.loc[:, 'champion_patch_winrate'] = win_rate

df

/var/folders/5w/5hzxm109285f2kz_4q6tm5yw0000gn/T/ipykernel_21103/1641571520.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.loc[:, 'champion_patch_winrate'] = win_rate

,gameid,datacompleteness,url,league,year,split,playoffs,date,game,patch,side,position,playername,teamname,result,champion,player_champ_winrate,champion_patch_winrate
824446,TRKR1/440018,complete,http://matchhistory.na.leagueoflegends.com/en/...,OGN,2015,Spring,0,2015-01-07 08:56:44,1.0,4.21,Blue,team,NaN,NaJin e-mFire,1,NaN,NaN,NaN
824445,TRKR1/440018,complete,http://matchhistory.na.leagueoflegends.com/en/...,OGN,2015,Spring,0,2015-01-07 08:56:44,1.0,4.21,Red,sup,Wolf,SK Telecom T1,0,Thresh,NaN,NaN
824444,TRKR1/440018,complete,http://matchhistory.na.leagueoflegends.com/en/...,OGN,2015,Spring,0,2015-01-07 08:56:44,1.0,4.21,Red,bot,Bang,SK Telecom T1,0,Tristana,NaN,NaN
824443,TRKR1/440018,complete,http://matchhistory.na.leagueoflegends.com/en/...,OGN,2015,Spring,0,2015-01-07 08:56:44,1.0,4.21,Red,mid,Faker,SK Telecom T1,0,Xerath,NaN,NaN
824442,TRKR1/440018,complete,http://matchhistory.na.leagueoflegends.com/en/...,OGN,2015,Spring,0,2015-01-07 08:56:44,1.0,4.21,Red,jng,Bengi,SK Telecom T1,0,Lee Sin,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
110252,ESPORTSTMNT04_2690755,complete,NaN,UL,2023,NaN,1,2023-08-04 18:01:54,4.0,13.14,Red,bot,Ice,Zero Tenacity,0,Xayah,0.750000,0.542683
110253,ESPORTSTMNT04_2690755,complete,NaN,UL,2023,NaN,1,2023-08-04 18:01:54,4.0,13.14,Red,sup,kabbie,Zero Tenacity,0,Nautilus,0.588235,0.500000
110254,ESPORTSTMNT04_2690755,complete,NaN,UL,2023,NaN,1,2023-08-04 18:01:54,4.0,13.14,Blue,team,NaN,Alior Bank Team,1,NaN,1.000000,0.964332
110255,ESPORTSTMNT04_2690755,complete,NaN,UL,2023,NaN,1,2023-08-04 18:01:54,4.0,13.14,Red,team,NaN,Zero Tenacity,0,NaN,1.000000,0.964332
110248,ESPORTSTMNT04_2690755,complete,NaN,UL,2023,NaN,1,2023-08-04 18:01:54,4.0,13.14,Blue,sup,minemaciek,Alior Bank Team,1,Rell,1.000000,0.416107

In [7]:
pivot = df.set_index(['gameid', 'position', 'side'])['champion']

pivot = pivot.reset_index()

side_map = {'Red': 'Blue', 'Blue': 'Red'}

pivot['opposite_side'] = pivot['side'].map(side_map)

df = pd.merge(df, pivot, left_on=['gameid', 'position', 'side'], 
              right_on=['gameid', 'position', 'opposite_side'], suffixes=('', '_y'))

df = df.drop(columns=['side_y', 'opposite_side'])

df = df.rename(columns={'champion_y': 'opposing_champion'})

df

,gameid,datacompleteness,url,league,year,split,playoffs,date,game,patch,side,position,playername,teamname,result,champion,player_champ_winrate,champion_patch_winrate,opposing_champion
0,TRKR1/440018,complete,http://matchhistory.na.leagueoflegends.com/en/...,OGN,2015,Spring,0,2015-01-07 08:56:44,1.0,4.21,Blue,team,NaN,NaJin e-mFire,1,NaN,NaN,NaN,NaN
1,TRKR1/440018,complete,http://matchhistory.na.leagueoflegends.com/en/...,OGN,2015,Spring,0,2015-01-07 08:56:44,1.0,4.21,Red,sup,Wolf,SK Telecom T1,0,Thresh,NaN,NaN,Annie
2,TRKR1/440018,complete,http://matchhistory.na.leagueoflegends.com/en/...,OGN,2015,Spring,0,2015-01-07 08:56:44,1.0,4.21,Red,bot,Bang,SK Telecom T1,0,Tristana,NaN,NaN,Sivir
3,TRKR1/440018,complete,http://matchhistory.na.leagueoflegends.com/en/...,OGN,2015,Spring,0,2015-01-07 08:56:44,1.0,4.21,Red,mid,Faker,SK Telecom T1,0,Xerath,NaN,NaN,Zed
4,TRKR1/440018,complete,http://matchhistory.na.leagueoflegends.com/en/...,OGN,2015,Spring,0,2015-01-07 08:56:44,1.0,4.21,Red,jng,Bengi,SK Telecom T1,0,Lee Sin,NaN,NaN,Jarvan IV
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
846583,ESPORTSTMNT04_2690755,complete,NaN,UL,2023,NaN,1,2023-08-04 18:01:54,4.0,13.14,Red,bot,Ice,Zero Tenacity,0,Xayah,0.750000,0.542683,Jinx
846584,ESPORTSTMNT04_2690755,complete,NaN,UL,2023,NaN,1,2023-08-04 18:01:54,4.0,13.14,Red,sup,kabbie,Zero Tenacity,0,Nautilus,0.588235,0.500000,Rell
846585,ESPORTSTMNT04_2690755,complete,NaN,UL,2023,NaN,1,2023-08-04 18:01:54,4.0,13.14,Blue,team,NaN,Alior Bank Team,1,NaN,1.000000,0.964332,NaN
846586,ESPORTSTMNT04_2690755,complete,NaN,UL,2023,NaN,1,2023-08-04 18:01:54,4.0,13.14,Red,team,NaN,Zero Tenacity,0,NaN,1.000000,0.964332,NaN
846587,ESPORTSTMNT04_2690755,complete,NaN,UL,2023,NaN,1,2023-08-04 18:01:54,4.0,13.14,Blue,sup,minemaciek,Alior Bank Team,1,Rell,1.000000,0.416107,Nautilus

In [8]:
df['date'] = pd.to_datetime(df['date'])

df.sort_values(by='date', inplace=True)

grouped = df.groupby(['champion', 'opposing_champion'])

total_games = grouped['result'].cumcount()
total_wins = grouped['result'].cumsum()

win_rate = total_wins / total_games

df['counter_winrate'] = win_rate

df

,gameid,datacompleteness,url,league,year,split,playoffs,date,game,patch,side,position,playername,teamname,result,champion,player_champ_winrate,champion_patch_winrate,opposing_champion,counter_winrate
0,TRKR1/440018,complete,http://matchhistory.na.leagueoflegends.com/en/...,OGN,2015,Spring,0,2015-01-07 08:56:44,1.0,4.21,Blue,team,NaN,NaJin e-mFire,1,NaN,NaN,NaN,NaN,inf
11,TRKR1/440018,complete,http://matchhistory.na.leagueoflegends.com/en/...,OGN,2015,Spring,0,2015-01-07 08:56:44,1.0,4.21,Blue,sup,Cain,NaJin e-mFire,1,Annie,inf,NaN,Thresh,inf
10,TRKR1/440018,complete,http://matchhistory.na.leagueoflegends.com/en/...,OGN,2015,Spring,0,2015-01-07 08:56:44,1.0,4.21,Blue,top,Duke,NaJin e-mFire,1,Rumble,inf,NaN,Dr. Mundo,inf
9,TRKR1/440018,complete,http://matchhistory.na.leagueoflegends.com/en/...,OGN,2015,Spring,0,2015-01-07 08:56:44,1.0,4.21,Blue,jng,Watch,NaJin e-mFire,1,Jarvan IV,inf,NaN,Lee Sin,inf
7,TRKR1/440018,complete,http://matchhistory.na.leagueoflegends.com/en/...,OGN,2015,Spring,0,2015-01-07 08:56:44,1.0,4.21,Blue,bot,Ohq,NaJin e-mFire,1,Sivir,inf,NaN,Tristana,inf
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
846577,ESPORTSTMNT04_2690755,complete,NaN,UL,2023,NaN,1,2023-08-04 18:01:54,4.0,13.14,Blue,jng,adi1,Alior Bank Team,1,Lillia,1.000,0.555556,Sejuani,0.506667
846576,ESPORTSTMNT04_2690755,complete,NaN,UL,2023,NaN,1,2023-08-04 18:01:54,4.0,13.14,Blue,top,Matixx,Alior Bank Team,1,Renekton,0.800,0.476190,Jax,0.502283
846586,ESPORTSTMNT04_2690755,complete,NaN,UL,2023,NaN,1,2023-08-04 18:01:54,4.0,13.14,Red,team,NaN,Zero Tenacity,0,NaN,1.000,0.964332,NaN,0.000000
846580,ESPORTSTMNT04_2690755,complete,NaN,UL,2023,NaN,1,2023-08-04 18:01:54,4.0,13.14,Red,top,Color,Zero Tenacity,0,Jax,0.625,0.547945,Renekton,0.500000
846587,ESPORTSTMNT04_2690755,complete,NaN,UL,2023,NaN,1,2023-08-04 18:01:54,4.0,13.14,Blue,sup,minemaciek,Alior Bank Team,1,Rell,1.000,0.416107,Nautilus,0.566351

In [9]:
df = df[df['position'] != 'team']
df

,gameid,datacompleteness,url,league,year,split,playoffs,date,game,patch,side,position,playername,teamname,result,champion,player_champ_winrate,champion_patch_winrate,opposing_champion,counter_winrate
11,TRKR1/440018,complete,http://matchhistory.na.leagueoflegends.com/en/...,OGN,2015,Spring,0,2015-01-07 08:56:44,1.0,4.21,Blue,sup,Cain,NaJin e-mFire,1,Annie,inf,NaN,Thresh,inf
10,TRKR1/440018,complete,http://matchhistory.na.leagueoflegends.com/en/...,OGN,2015,Spring,0,2015-01-07 08:56:44,1.0,4.21,Blue,top,Duke,NaJin e-mFire,1,Rumble,inf,NaN,Dr. Mundo,inf
9,TRKR1/440018,complete,http://matchhistory.na.leagueoflegends.com/en/...,OGN,2015,Spring,0,2015-01-07 08:56:44,1.0,4.21,Blue,jng,Watch,NaJin e-mFire,1,Jarvan IV,inf,NaN,Lee Sin,inf
7,TRKR1/440018,complete,http://matchhistory.na.leagueoflegends.com/en/...,OGN,2015,Spring,0,2015-01-07 08:56:44,1.0,4.21,Blue,bot,Ohq,NaJin e-mFire,1,Sivir,inf,NaN,Tristana,inf
8,TRKR1/440018,complete,http://matchhistory.na.leagueoflegends.com/en/...,OGN,2015,Spring,0,2015-01-07 08:56:44,1.0,4.21,Blue,mid,Ggoong,NaJin e-mFire,1,Zed,inf,NaN,Xerath,inf
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
846579,ESPORTSTMNT04_2690755,complete,NaN,UL,2023,NaN,1,2023-08-04 18:01:54,4.0,13.14,Blue,bot,svns,Alior Bank Team,1,Jinx,0.555556,0.368421,Xayah,0.485965
846577,ESPORTSTMNT04_2690755,complete,NaN,UL,2023,NaN,1,2023-08-04 18:01:54,4.0,13.14,Blue,jng,adi1,Alior Bank Team,1,Lillia,1.000000,0.555556,Sejuani,0.506667
846576,ESPORTSTMNT04_2690755,complete,NaN,UL,2023,NaN,1,2023-08-04 18:01:54,4.0,13.14,Blue,top,Matixx,Alior Bank Team,1,Renekton,0.800000,0.476190,Jax,0.502283
846580,ESPORTSTMNT04_2690755,complete,NaN,UL,2023,NaN,1,2023-08-04 18:01:54,4.0,13.14,Red,top,Color,Zero Tenacity,0,Jax,0.625000,0.547945,Renekton,0.500000
846587,ESPORTSTMNT04_2690755,complete,NaN,UL,2023,NaN,1,2023-08-04 18:01:54,4.0,13.14,Blue,sup,minemaciek,Alior Bank Team,1,Rell,1.000000,0.416107,Nautilus,0.566351

In [10]:
df = df.drop(['league', 'year', 'split', 'playoffs', 'opposing_champion'], axis=1)
df

,gameid,datacompleteness,url,date,game,patch,side,position,playername,teamname,result,champion,player_champ_winrate,champion_patch_winrate,counter_winrate
11,TRKR1/440018,complete,http://matchhistory.na.leagueoflegends.com/en/...,2015-01-07 08:56:44,1.0,4.21,Blue,sup,Cain,NaJin e-mFire,1,Annie,inf,NaN,inf
10,TRKR1/440018,complete,http://matchhistory.na.leagueoflegends.com/en/...,2015-01-07 08:56:44,1.0,4.21,Blue,top,Duke,NaJin e-mFire,1,Rumble,inf,NaN,inf
9,TRKR1/440018,complete,http://matchhistory.na.leagueoflegends.com/en/...,2015-01-07 08:56:44,1.0,4.21,Blue,jng,Watch,NaJin e-mFire,1,Jarvan IV,inf,NaN,inf
7,TRKR1/440018,complete,http://matchhistory.na.leagueoflegends.com/en/...,2015-01-07 08:56:44,1.0,4.21,Blue,bot,Ohq,NaJin e-mFire,1,Sivir,inf,NaN,inf
8,TRKR1/440018,complete,http://matchhistory.na.leagueoflegends.com/en/...,2015-01-07 08:56:44,1.0,4.21,Blue,mid,Ggoong,NaJin e-mFire,1,Zed,inf,NaN,inf
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
846579,ESPORTSTMNT04_2690755,complete,NaN,2023-08-04 18:01:54,4.0,13.14,Blue,bot,svns,Alior Bank Team,1,Jinx,0.555556,0.368421,0.485965
846577,ESPORTSTMNT04_2690755,complete,NaN,2023-08-04 18:01:54,4.0,13.14,Blue,jng,adi1,Alior Bank Team,1,Lillia,1.000000,0.555556,0.506667
846576,ESPORTSTMNT04_2690755,complete,NaN,2023-08-04 18:01:54,4.0,13.14,Blue,top,Matixx,Alior Bank Team,1,Renekton,0.800000,0.476190,0.502283
846580,ESPORTSTMNT04_2690755,complete,NaN,2023-08-04 18:01:54,4.0,13.14,Red,top,Color,Zero Tenacity,0,Jax,0.625000,0.547945,0.500000
846587,ESPORTSTMNT04_2690755,complete,NaN,2023-08-04 18:01:54,4.0,13.14,Blue,sup,minemaciek,Alior Bank Team,1,Rell,1.000000,0.416107,0.566351

In [11]:
df.dropna(subset=['player_champ_winrate', 'champion_patch_winrate', 'counter_winrate'], inplace=True)
df.replace([np.inf, -np.inf], np.nan, inplace=True)
df.dropna(inplace=True)
df

,gameid,datacompleteness,url,date,game,patch,side,position,playername,teamname,result,champion,player_champ_winrate,champion_patch_winrate,counter_winrate
23,TRKR1/450030,complete,http://matchhistory.na.leagueoflegends.com/en/...,2015-01-07 10:07:23,2.0,4.21,Blue,jng,Bengi,SK Telecom T1,1,Lee Sin,1.000000,1.000000,1.000000
18,TRKR1/450030,complete,http://matchhistory.na.leagueoflegends.com/en/...,2015-01-07 10:07:23,2.0,4.21,Red,jng,Watch,NaJin e-mFire,0,Jarvan IV,1.000000,1.000000,1.000000
115,TRTW/70074,complete,http://matchhistory.na.leagueoflegends.com/en/...,2015-01-09 11:01:26,1.0,4.21,Blue,bot,3z,Logitech G Snipers,0,Sivir,1.000000,0.500000,1.000000
114,TRTW/70074,complete,http://matchhistory.na.leagueoflegends.com/en/...,2015-01-09 11:01:26,1.0,4.21,Blue,sup,K,Logitech G Snipers,0,Janna,1.000000,0.750000,0.000000
138,TRTW/60055,complete,http://matchhistory.na.leagueoflegends.com/en/...,2015-01-09 12:12:48,1.0,4.21,Blue,sup,Rain,DarlingYou,0,Thresh,1.000000,0.571429,1.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
846212,10405-10405_game_3,partial,https://lpl.qq.com/es/stats.shtml?bmid=10405,2023-08-04 08:16:29,3.0,13.13,Blue,bot,Such,MAX,1,Kai'Sa,0.656250,0.518325,0.600000
846211,10405-10405_game_3,partial,https://lpl.qq.com/es/stats.shtml?bmid=10405,2023-08-04 08:16:29,3.0,13.13,Blue,sup,Vinay,MAX,1,Alistar,0.714286,0.495652,1.000000
846210,10405-10405_game_3,partial,https://lpl.qq.com/es/stats.shtml?bmid=10405,2023-08-04 08:16:29,3.0,13.13,Red,top,Wen,Invictus Gaming Young,0,Gwen,0.727273,0.449275,0.500000
846208,10405-10405_game_3,partial,https://lpl.qq.com/es/stats.shtml?bmid=10405,2023-08-04 08:16:29,3.0,13.13,Red,mid,MG,Invictus Gaming Young,0,Taliyah,0.933333,0.560000,0.600000
846209,10405-10405_game_3,partial,https://lpl.qq.com/es/stats.shtml?bmid=10405,2023-08-04 08:16:29,3.0,13.13,Red,jng,Liweier,Invictus Gaming Young,0,Vi,0.714286,0.379310,0.461538

In [12]:
avg_win_rate = df.groupby(['teamname', 'gameid'])[['player_champ_winrate', 'champion_patch_winrate', 'counter_winrate']].mean()

avg_win_rate.columns = ['avg_player_champ_winrate', 'avg_champion_patch_winrate', 'avg_counter_winrate']

df = df.merge(avg_win_rate, on=['teamname', 'gameid'])

df

,gameid,datacompleteness,url,date,game,patch,side,position,playername,teamname,result,champion,player_champ_winrate,champion_patch_winrate,counter_winrate,avg_player_champ_winrate,avg_champion_patch_winrate,avg_counter_winrate
0,TRKR1/450030,complete,http://matchhistory.na.leagueoflegends.com/en/...,2015-01-07 10:07:23,2.0,4.21,Blue,jng,Bengi,SK Telecom T1,1,Lee Sin,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
1,TRKR1/450030,complete,http://matchhistory.na.leagueoflegends.com/en/...,2015-01-07 10:07:23,2.0,4.21,Red,jng,Watch,NaJin e-mFire,0,Jarvan IV,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
2,TRTW/70074,complete,http://matchhistory.na.leagueoflegends.com/en/...,2015-01-09 11:01:26,1.0,4.21,Blue,bot,3z,Logitech G Snipers,0,Sivir,1.000000,0.500000,1.000000,1.000000,0.625000,0.500000
3,TRTW/70074,complete,http://matchhistory.na.leagueoflegends.com/en/...,2015-01-09 11:01:26,1.0,4.21,Blue,sup,K,Logitech G Snipers,0,Janna,1.000000,0.750000,0.000000,1.000000,0.625000,0.500000
4,TRTW/60055,complete,http://matchhistory.na.leagueoflegends.com/en/...,2015-01-09 12:12:48,1.0,4.21,Blue,sup,Rain,DarlingYou,0,Thresh,1.000000,0.571429,1.000000,1.000000,0.571429,1.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
400942,10405-10405_game_3,partial,https://lpl.qq.com/es/stats.shtml?bmid=10405,2023-08-04 08:16:29,3.0,13.13,Blue,bot,Such,MAX,1,Kai'Sa,0.656250,0.518325,0.600000,0.728515,0.481394,0.626583
400943,10405-10405_game_3,partial,https://lpl.qq.com/es/stats.shtml?bmid=10405,2023-08-04 08:16:29,3.0,13.13,Blue,sup,Vinay,MAX,1,Alistar,0.714286,0.495652,1.000000,0.728515,0.481394,0.626583
400944,10405-10405_game_3,partial,https://lpl.qq.com/es/stats.shtml?bmid=10405,2023-08-04 08:16:29,3.0,13.13,Red,top,Wen,Invictus Gaming Young,0,Gwen,0.727273,0.449275,0.500000,0.791631,0.462862,0.520513
400945,10405-10405_game_3,partial,https://lpl.qq.com/es/stats.shtml?bmid=10405,2023-08-04 08:16:29,3.0,13.13,Red,mid,MG,Invictus Gaming Young,0,Taliyah,0.933333,0.560000,0.600000,0.791631,0.462862,0.520513
400946,10405-10405_game_3,partial,https://lpl.qq.com/es/stats.shtml?bmid=10405,2023-08-04 08:16:29,3.0,13.13,Red,jng,Liweier,Invictus Gaming Young,0,Vi,0.714286,0.379310,0.461538,0.791631,0.462862,0.520513

In [13]:
import pandas as pd

df = df.drop_duplicates(subset=['teamname', 'gameid'])

df

,gameid,datacompleteness,url,date,game,patch,side,position,playername,teamname,result,champion,player_champ_winrate,champion_patch_winrate,counter_winrate,avg_player_champ_winrate,avg_champion_patch_winrate,avg_counter_winrate
0,TRKR1/450030,complete,http://matchhistory.na.leagueoflegends.com/en/...,2015-01-07 10:07:23,2.0,4.21,Blue,jng,Bengi,SK Telecom T1,1,Lee Sin,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
1,TRKR1/450030,complete,http://matchhistory.na.leagueoflegends.com/en/...,2015-01-07 10:07:23,2.0,4.21,Red,jng,Watch,NaJin e-mFire,0,Jarvan IV,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
2,TRTW/70074,complete,http://matchhistory.na.leagueoflegends.com/en/...,2015-01-09 11:01:26,1.0,4.21,Blue,bot,3z,Logitech G Snipers,0,Sivir,1.000000,0.500000,1.000000,1.000000,0.625000,0.500000
4,TRTW/60055,complete,http://matchhistory.na.leagueoflegends.com/en/...,2015-01-09 12:12:48,1.0,4.21,Blue,sup,Rain,DarlingYou,0,Thresh,1.000000,0.571429,1.000000,1.000000,0.571429,1.000000
5,TRTW/60055,complete,http://matchhistory.na.leagueoflegends.com/en/...,2015-01-09 12:12:48,1.0,4.21,Red,bot,An,ahq eSports Club,1,Corki,2.000000,1.000000,2.000000,2.000000,1.000000,2.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
400924,10405-10405_game_1,partial,https://lpl.qq.com/es/stats.shtml?bmid=10405,2023-08-04 06:17:34,1.0,13.13,Red,top,Wen,Invictus Gaming Young,0,Renekton,0.400000,0.489157,0.498851,0.579710,0.491596,0.495378
400929,10405-10405_game_2,partial,https://lpl.qq.com/es/stats.shtml?bmid=10405,2023-08-04 07:17:26,2.0,13.13,Blue,sup,WuNai,Invictus Gaming Young,0,Nautilus,0.818182,0.430952,0.434368,0.563041,0.505692,0.472379
400934,10405-10405_game_2,partial,https://lpl.qq.com/es/stats.shtml?bmid=10405,2023-08-04 07:17:26,2.0,13.13,Red,top,Garvey,MAX,1,Rumble,1.250000,0.526012,0.617647,0.894425,0.533631,0.537783
400939,10405-10405_game_3,partial,https://lpl.qq.com/es/stats.shtml?bmid=10405,2023-08-04 08:16:29,3.0,13.13,Blue,top,Garvey,MAX,1,K'Sante,0.695652,0.462025,0.503247,0.728515,0.481394,0.626583
400944,10405-10405_game_3,partial,https://lpl.qq.com/es/stats.shtml?bmid=10405,2023-08-04 08:16:29,3.0,13.13,Red,top,Wen,Invictus Gaming Young,0,Gwen,0.727273,0.449275,0.500000,0.791631,0.462862,0.520513

In [14]:
df = df[['gameid', 'side','teamname', 'result', 'avg_player_champ_winrate', 'avg_champion_patch_winrate', 'avg_counter_winrate']]

df

,gameid,side,teamname,result,avg_player_champ_winrate,avg_champion_patch_winrate,avg_counter_winrate
0,TRKR1/450030,Blue,SK Telecom T1,1,1.000000,1.000000,1.000000
1,TRKR1/450030,Red,NaJin e-mFire,0,1.000000,1.000000,1.000000
2,TRTW/70074,Blue,Logitech G Snipers,0,1.000000,0.625000,0.500000
4,TRTW/60055,Blue,DarlingYou,0,1.000000,0.571429,1.000000
5,TRTW/60055,Red,ahq eSports Club,1,2.000000,1.000000,2.000000
...,...,...,...,...,...,...,...
400924,10405-10405_game_1,Red,Invictus Gaming Young,0,0.579710,0.491596,0.495378
400929,10405-10405_game_2,Blue,Invictus Gaming Young,0,0.563041,0.505692,0.472379
400934,10405-10405_game_2,Red,MAX,1,0.894425,0.533631,0.537783
400939,10405-10405_game_3,Blue,MAX,1,0.728515,0.481394,0.626583
400944,10405-10405_game_3,Red,Invictus Gaming Young,0,0.791631,0.462862,0.520513

In [15]:
import pandas as pd

pivot = df.set_index(['gameid', 'side'])['avg_player_champ_winrate']

pivot = pivot.reset_index()

side_map = {'Red': 'Blue', 'Blue': 'Red'}

pivot['opposite_side'] = pivot['side'].map(side_map)

df = pd.merge(df, pivot, left_on=['gameid', 'side'],
              right_on=['gameid', 'opposite_side'], suffixes=('', '_y'))

df = df.drop(columns=['side_y', 'opposite_side'])

df = df.rename(columns={'avg_player_champ_winrate_y': 'opposing_avg_player_champ_winrate'})

df

,gameid,side,teamname,result,avg_player_champ_winrate,avg_champion_patch_winrate,avg_counter_winrate,opposing_avg_player_champ_winrate
0,TRKR1/450030,Blue,SK Telecom T1,1,1.000000,1.000000,1.000000,1.000000
1,TRKR1/450030,Red,NaJin e-mFire,0,1.000000,1.000000,1.000000,1.000000
2,TRTW/60055,Blue,DarlingYou,0,1.000000,0.571429,1.000000,2.000000
3,TRTW/60055,Red,ahq eSports Club,1,2.000000,1.000000,2.000000,1.000000
4,TRKR1/450078,Blue,Samsung Galaxy,0,0.666667,0.398148,0.533333,1.333333
...,...,...,...,...,...,...,...,...
99409,10405-10405_game_1,Red,Invictus Gaming Young,0,0.579710,0.491596,0.495378,0.687302
99410,10405-10405_game_2,Blue,Invictus Gaming Young,0,0.563041,0.505692,0.472379,0.894425
99411,10405-10405_game_2,Red,MAX,1,0.894425,0.533631,0.537783,0.563041
99412,10405-10405_game_3,Blue,MAX,1,0.728515,0.481394,0.626583,0.791631
99413,10405-10405_game_3,Red,Invictus Gaming Young,0,0.791631,0.462862,0.520513,0.728515

In [16]:
import pandas as pd

pivot = df.set_index(['gameid', 'side'])['avg_champion_patch_winrate']

pivot = pivot.reset_index()

side_map = {'Red': 'Blue', 'Blue': 'Red'}

pivot['opposite_side'] = pivot['side'].map(side_map)

df = pd.merge(df, pivot, left_on=['gameid', 'side'],
              right_on=['gameid', 'opposite_side'], suffixes=('', '_y'))

df = df.drop(columns=['side_y', 'opposite_side'])

df = df.rename(columns={'avg_champion_patch_winrate_y': 'opposing_avg_champion_patch_winrate'})

df

,gameid,side,teamname,result,avg_player_champ_winrate,avg_champion_patch_winrate,avg_counter_winrate,opposing_avg_player_champ_winrate,opposing_avg_champion_patch_winrate
0,TRKR1/450030,Blue,SK Telecom T1,1,1.000000,1.000000,1.000000,1.000000,1.000000
1,TRKR1/450030,Red,NaJin e-mFire,0,1.000000,1.000000,1.000000,1.000000,1.000000
2,TRTW/60055,Blue,DarlingYou,0,1.000000,0.571429,1.000000,2.000000,1.000000
3,TRTW/60055,Red,ahq eSports Club,1,2.000000,1.000000,2.000000,1.000000,0.571429
4,TRKR1/450078,Blue,Samsung Galaxy,0,0.666667,0.398148,0.533333,1.333333,0.833333
...,...,...,...,...,...,...,...,...,...
99409,10405-10405_game_1,Red,Invictus Gaming Young,0,0.579710,0.491596,0.495378,0.687302,0.486106
99410,10405-10405_game_2,Blue,Invictus Gaming Young,0,0.563041,0.505692,0.472379,0.894425,0.533631
99411,10405-10405_game_2,Red,MAX,1,0.894425,0.533631,0.537783,0.563041,0.505692
99412,10405-10405_game_3,Blue,MAX,1,0.728515,0.481394,0.626583,0.791631,0.462862
99413,10405-10405_game_3,Red,Invictus Gaming Young,0,0.791631,0.462862,0.520513,0.728515,0.481394

In [17]:
pivot = df.set_index(['gameid', 'side'])['avg_counter_winrate']

pivot = pivot.reset_index()

side_map = {'Red': 'Blue', 'Blue': 'Red'}

pivot['opposite_side'] = pivot['side'].map(side_map)

df = pd.merge(df, pivot, left_on=['gameid', 'side'],
              right_on=['gameid', 'opposite_side'], suffixes=('', '_y'))

df = df.drop(columns=['side_y', 'opposite_side'])

df = df.rename(columns={'avg_counter_winrate_y': 'opposing_avg_counter_winrate'})

df

,gameid,side,teamname,result,avg_player_champ_winrate,avg_champion_patch_winrate,avg_counter_winrate,opposing_avg_player_champ_winrate,opposing_avg_champion_patch_winrate,opposing_avg_counter_winrate
0,TRKR1/450030,Blue,SK Telecom T1,1,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
1,TRKR1/450030,Red,NaJin e-mFire,0,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
2,TRTW/60055,Blue,DarlingYou,0,1.000000,0.571429,1.000000,2.000000,1.000000,2.000000
3,TRTW/60055,Red,ahq eSports Club,1,2.000000,1.000000,2.000000,1.000000,0.571429,1.000000
4,TRKR1/450078,Blue,Samsung Galaxy,0,0.666667,0.398148,0.533333,1.333333,0.833333,1.200000
...,...,...,...,...,...,...,...,...,...,...
99409,10405-10405_game_1,Red,Invictus Gaming Young,0,0.579710,0.491596,0.495378,0.687302,0.486106,0.506965
99410,10405-10405_game_2,Blue,Invictus Gaming Young,0,0.563041,0.505692,0.472379,0.894425,0.533631,0.537783
99411,10405-10405_game_2,Red,MAX,1,0.894425,0.533631,0.537783,0.563041,0.505692,0.472379
99412,10405-10405_game_3,Blue,MAX,1,0.728515,0.481394,0.626583,0.791631,0.462862,0.520513
99413,10405-10405_game_3,Red,Invictus Gaming Young,0,0.791631,0.462862,0.520513,0.728515,0.481394,0.626583

In [18]:
df['difference_avg_player_champ_winrate'] = pd.NA
df['difference_avg_champion_patch_winrate'] = pd.NA
df['difference_avg_counter_winrate'] = pd.NA

df['difference_avg_player_champ_winrate'] = df['avg_player_champ_winrate'] - df['opposing_avg_player_champ_winrate']
df['difference_avg_champion_patch_winrate'] = df['avg_champion_patch_winrate'] - df['opposing_avg_champion_patch_winrate']
df['difference_avg_counter_winrate'] = df['avg_counter_winrate'] - df['opposing_avg_counter_winrate']

df

,gameid,side,teamname,result,avg_player_champ_winrate,avg_champion_patch_winrate,avg_counter_winrate,opposing_avg_player_champ_winrate,opposing_avg_champion_patch_winrate,opposing_avg_counter_winrate,difference_avg_player_champ_winrate,difference_avg_champion_patch_winrate,difference_avg_counter_winrate
0,TRKR1/450030,Blue,SK Telecom T1,1,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000
1,TRKR1/450030,Red,NaJin e-mFire,0,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000
2,TRTW/60055,Blue,DarlingYou,0,1.000000,0.571429,1.000000,2.000000,1.000000,2.000000,-1.000000,-0.428571,-1.000000
3,TRTW/60055,Red,ahq eSports Club,1,2.000000,1.000000,2.000000,1.000000,0.571429,1.000000,1.000000,0.428571,1.000000
4,TRKR1/450078,Blue,Samsung Galaxy,0,0.666667,0.398148,0.533333,1.333333,0.833333,1.200000,-0.666667,-0.435185,-0.666667
...,...,...,...,...,...,...,...,...,...,...,...,...,...
99409,10405-10405_game_1,Red,Invictus Gaming Young,0,0.579710,0.491596,0.495378,0.687302,0.486106,0.506965,-0.107591,0.005490,-0.011587
99410,10405-10405_game_2,Blue,Invictus Gaming Young,0,0.563041,0.505692,0.472379,0.894425,0.533631,0.537783,-0.331383,-0.027939,-0.065403
99411,10405-10405_game_2,Red,MAX,1,0.894425,0.533631,0.537783,0.563041,0.505692,0.472379,0.331383,0.027939,0.065403
99412,10405-10405_game_3,Blue,MAX,1,0.728515,0.481394,0.626583,0.791631,0.462862,0.520513,-0.063115,0.018532,0.106071
99413,10405-10405_game_3,Red,Invictus Gaming Young,0,0.791631,0.462862,0.520513,0.728515,0.481394,0.626583,0.063115,-0.018532,-0.106071

In [19]:
df = df.drop(columns=['avg_player_champ_winrate', 'avg_champion_patch_winrate', 'avg_counter_winrate',
                      'opposing_avg_player_champ_winrate', 'opposing_avg_champion_patch_winrate',
                      'opposing_avg_counter_winrate'])

In [20]:
cleaned_data = df

In [21]:
cleaned_data.to_csv('/Users/micah.mathews/Documents/wager_ai/lol_data/data_cleaning/cleaned_data.csv', index=False)